version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/"
      target-branch: "main"
      open-pull-requests-limit: 10
      schedule:
          timezone: "Europe/Warsaw"
          interval: "weekly"
      commit-message:
          prefix: "chore(deps):"
      labels: ["🔄 dependencies"]
      groups:
          npm-workspace:
              patterns:
                  - "*"

    - package-ecosystem: "github-actions"
      directory: "/"
      target-branch: "main"
      open-pull-requests-limit: 10
      schedule:
          timezone: "Europe/Warsaw"
          interval: "weekly"
      commit-message:
          prefix: "chore(deps->actions):"
      labels: ["🔄 dependencies"]
      groups:
          github-actions:
              patterns:
                  - "*"
