import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const rootDir = resolve(import.meta.dir, "..");
const bootstrapPath = resolve(rootDir, "src/core/script-bootstrap.ts");
const outputPath = resolve(rootDir, "src/core/script-source.ts");
const checkOnly = process.argv.includes("--check");

function extractMinifiedFunction(bundle: string): string {
	const start = bundle.search(/function\s+\w+\s*\(/u);
	if (start < 0) {
		throw new Error("Expected Bun minify output to contain a named function declaration");
	}

	const bodyStart = bundle.indexOf("{", start);
	if (bodyStart < 0) {
		throw new Error("Expected minified bootstrap function to have a body");
	}

	let depth = 0;
	let inString: '"' | "'" | "`" | null = null;
	let escaped = false;
	let templateExprDepth = 0;

	for (let index = bodyStart; index < bundle.length; index += 1) {
		const char = bundle[index];
		const next = bundle[index + 1];

		if (inString === "`") {
			if (templateExprDepth > 0) {
				if (char === "{") templateExprDepth += 1;
				if (char === "}") templateExprDepth -= 1;
				continue;
			}
			if (escaped) {
				escaped = false;
				continue;
			}
			if (char === "\\") {
				escaped = true;
				continue;
			}
			if (char === "`") {
				inString = null;
				continue;
			}
			if (char === "$" && next === "{") {
				templateExprDepth = 1;
				index += 1;
				continue;
			}
			continue;
		}

		if (inString) {
			if (escaped) {
				escaped = false;
				continue;
			}
			if (char === "\\") {
				escaped = true;
				continue;
			}
			if (char === inString) inString = null;
			continue;
		}

		if (char === '"' || char === "'" || char === "`") {
			inString = char;
			continue;
		}
		if (char === "{") depth += 1;
		if (char === "}") {
			depth -= 1;
			if (depth === 0) {
				const declaration = bundle.slice(start, index + 1);
				// IIFE-friendly anonymous function expression: (function(...){...})(args)
				return declaration.replace(/^function\s+\w+/u, "function");
			}
		}
	}

	throw new Error("Failed to find the end of the minified bootstrap function");
}

function renderSourceFile(minified: string): string {
	return `/** Generated by scripts/generate-script-source.ts — edit script-bootstrap.ts instead. */
export const THEME_SCRIPT_SOURCE: string = ${JSON.stringify(minified)};
`;
}

async function minifyBootstrap(): Promise<string> {
	const result = await Bun.build({
		entrypoints: [bootstrapPath],
		minify: true,
		target: "browser",
		write: false,
	});

	if (!result.success) {
		const messages = result.logs.map((log) => log.message ?? String(log)).join("\n");
		throw new Error(`Failed to minify theme bootstrap:\n${messages}`);
	}

	const output = result.outputs[0];
	if (!output) {
		throw new Error("Bun.build produced no minify output for theme bootstrap");
	}

	return extractMinifiedFunction(await output.text());
}

const minified = await minifyBootstrap();
const nextContents = renderSourceFile(minified);

if (checkOnly) {
	let current = "";
	try {
		current = await readFile(outputPath, "utf8");
	} catch {
		current = "";
	}

	if (current !== nextContents) {
		console.error(
			"src/core/script-source.ts is out of date. Run `bun scripts/generate-script-source.ts`.",
		);
		process.exit(1);
	}

	console.log("src/core/script-source.ts is up to date.");
	process.exit(0);
}

await mkdir(dirname(outputPath), { recursive: true });
await writeFile(outputPath, nextContents);
console.log(`Wrote ${outputPath}`);
