import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";

const rootDir = resolve(import.meta.dir, "..");
const checkOnly = process.argv.includes("--check");

const targets = [
	{
		bootstrapPath: resolve(rootDir, "src/core/script-bootstrap.ts"),
		outputPath: resolve(rootDir, "src/core/script-source.ts"),
		displayPath: "src/core/script-source.ts",
		readableName: "script-bootstrap.ts",
		exportName: "THEME_SCRIPT_SOURCE",
		label: "theme bootstrap",
	},
	{
		bootstrapPath: resolve(rootDir, "src/core/extended-script-bootstrap.ts"),
		outputPath: resolve(rootDir, "src/core/extended-script-source.ts"),
		displayPath: "src/core/extended-script-source.ts",
		readableName: "extended-script-bootstrap.ts",
		exportName: "EXTENDED_THEME_SCRIPT_SOURCE",
		label: "extended theme bootstrap",
	},
] as const;

type SourceTarget = (typeof targets)[number];

function extractMinifiedFunction(bundle: string): string {
	const start = bundle.search(/function\s+\w+\s*\(/u);
	if (start < 0) {
		throw new Error("Expected Bun minify output to contain a named function declaration");
	}

	const bodyStart = bundle.indexOf("{", start);
	if (bodyStart < 0) {
		throw new Error("Expected minified bootstrap function to have a body");
	}

	let depth = 0;
	let inString: '"' | "'" | "`" | null = null;
	let escaped = false;
	let templateExprDepth = 0;

	for (let index = bodyStart; index < bundle.length; index += 1) {
		const char = bundle[index];
		const next = bundle[index + 1];

		if (inString === "`") {
			if (templateExprDepth > 0) {
				if (char === "{") templateExprDepth += 1;
				if (char === "}") templateExprDepth -= 1;
				continue;
			}
			if (escaped) {
				escaped = false;
				continue;
			}
			if (char === "\\") {
				escaped = true;
				continue;
			}
			if (char === "`") {
				inString = null;
				continue;
			}
			if (char === "$" && next === "{") {
				templateExprDepth = 1;
				index += 1;
				continue;
			}
			continue;
		}

		if (inString) {
			if (escaped) {
				escaped = false;
				continue;
			}
			if (char === "\\") {
				escaped = true;
				continue;
			}
			if (char === inString) inString = null;
			continue;
		}

		if (char === '"' || char === "'" || char === "`") {
			inString = char;
			continue;
		}
		if (char === "{") depth += 1;
		if (char === "}") {
			depth -= 1;
			if (depth === 0) {
				const declaration = bundle.slice(start, index + 1);
				// IIFE-friendly anonymous function expression: (function(...){...})(args)
				return declaration.replace(/^function\s+\w+/u, "function");
			}
		}
	}

	throw new Error("Failed to find the end of the minified bootstrap function");
}

function renderSourceFile(target: SourceTarget, minified: string): string {
	return `/** Generated by scripts/generate-script-source.ts — edit ${target.readableName} instead. */
export const ${target.exportName}: string = ${JSON.stringify(minified)};
`;
}

async function minifyBootstrap(target: SourceTarget): Promise<string> {
	const result = await Bun.build({
		entrypoints: [target.bootstrapPath],
		minify: true,
		target: "browser",
		write: false,
	});

	if (!result.success) {
		const messages = result.logs.map((log) => log.message ?? String(log)).join("\n");
		throw new Error(`Failed to minify ${target.label}:\n${messages}`);
	}

	const output = result.outputs[0];
	if (!output) {
		throw new Error(`Bun.build produced no minify output for ${target.label}`);
	}

	return extractMinifiedFunction(await output.text());
}

const generated = await Promise.all(
	targets.map(async (target) => ({
		target,
		contents: renderSourceFile(target, await minifyBootstrap(target)),
	})),
);

if (checkOnly) {
	const stalePaths: string[] = [];
	for (const { target, contents } of generated) {
		let current = "";
		try {
			current = await readFile(target.outputPath, "utf8");
		} catch {
			current = "";
		}
		if (current !== contents) stalePaths.push(target.displayPath);
	}

	if (stalePaths.length > 0) {
		console.error(
			`${stalePaths.join(", ")} ${stalePaths.length === 1 ? "is" : "are"} out of date. Run \`bun scripts/generate-script-source.ts\`.`,
		);
		process.exit(1);
	}

	console.log("Generated script sources are up to date.");
	process.exit(0);
}

for (const { target, contents } of generated) {
	await mkdir(dirname(target.outputPath), { recursive: true });
	await writeFile(target.outputPath, contents);
	console.log(`Wrote ${target.outputPath}`);
}
